version: '3.8'
x-common:
  database:
    &db-env
    MYSQL_PASSWORD: &db-password "CHANGE_ME"
    MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO"
  panel:
    &pm-env
    APP_NAME: Paymenter
    APP_ENV: production
    APP_URL: http://example.com
    LE_EMAIL: "admin@example.com"
    LOG_CHANNEL: stack
    LOG_DEPRECATIONS_CHANNEL: null
    LOG_LEVEL: debug
    DB_CONNECTION: mysql
    DB_HOST: database
    DB_PORT: 3306
    DB_DATABASE: paymenter
    DB_USERNAME: paymenter
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    FILESYSTEM_DISK: local
    QUEUE_CONNECTION: database
    SESSION_DRIVER: file
    SESSION_LIFETIME: 120
    MEMCACHED_HOST: cache

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      <<: *db-env
      MYSQL_DATABASE: "paymenter"
      MYSQL_USER: "paymenter"
  cache:
    image: redis:alpine
    restart: always
  paymenter:
    image: paymenter:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    volumes:
      - "var:/app/var/"
      - "nginx:/etc/nginx/http.d"
      - "certs:/etc/letsencrypt/"
      - "logs:/app/storage/logs"
    environment:
      <<: *pm-env
      DB_PASSWORD: *db-password 
volumes:
  mysql:
  var:
  nginx:
  certs:
  logs:
networks:
  default:
    ipam:
      config:
        - subnet: 172.23.0.0/16
