<?php

use App\Helpers\ExtensionHelper;
use Illuminate\Support\Facades\Http;

function Proxmox_getConfig()
{
    return [
        [
            'name' => 'host',
            'friendlyName' => 'Url to Proxmox server',
            'type' => 'text',
            'required' => true,
        ],
        [
            'name' => 'username',
            'friendlyName' => 'Username',
            'type' => 'text',
            'required' => true,
        ],
        [
            'name' => 'password',
            'friendlyName' => 'Password',
            'type' => 'text',
            'required' => true,

        ]
    ];
}

function Proxmox_getProductConfig()
{
    return [
        [
            'name' => 'vmId',
            'friendlyName' => 'VM ID',
            'type' => 'text',
            'required' => true,
            'description' => 'VM ID for the Proxmox server',
        ],
    ];
}

function getAccessKey(){
    $response = Http::post(ExtensionHelper::getConfig('Proxmox', 'host') . '/api2/json/access/ticket', [
        'username' => ExtensionHelper::getConfig('Proxmox', 'username'),
        'password' => ExtensionHelper::getConfig('Proxmox', 'password'),
    ]);
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, ExtensionHelper::getConfig('Proxmox', 'host') . '/api2/json/access/ticket');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, 'username=' . ExtensionHelper::getConfig('Proxmox', 'username'));
    curl_setopt($ch, CURLOPT_POSTFIELDS, 'password=' . ExtensionHelper::getConfig('Proxmox', 'password'));  

    $headers = array();
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    dd($result);
    $response = json_decode($response->body());
    return $response->data->ticket;

}

function Proxmox_createServer($user, $params, $order)
{
    dd(getAccessKey());
}