name: Laravel

on:
  [push, pull_request]


jobs:
  laravel-tests:
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: paymenter_test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run migrations
      run: php artisan migrate --force --seed
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: paymenter_test
        DB_USERNAME: root
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install NPM dependencies
      run: npm install
    - name: Build Vite
      run: npm run build
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: paymenter_test
        DB_USERNAME: root
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: vendor/bin/phpunit
